---
- name: Test playbook to run 
  hosts: all
  user: ec2-user
  become: true
  become_method: sudo
  tasks:
  - name: Download foo.conf
    ansible.builtin.get_url:
      url: http://wordpress.org/latest.tar.gz
      dest: /tmp/
      mode: '0440'

  - name: Unarchive a file that is already on the remote machine
    ansible.builtin.unarchive:
      src: /tmp/wordpress-6.1.1.tar.gz
      dest: /tmp/
      remote_src: yes



