---
- name: Test playbook to run 
  hosts: all
  user: ec2-user
  become: true
  become_method: sudo
  tasks:
  - name: Print all available facts
    when: ansible_facts['kernel'] == "4.14.232-177.418.amzn2.x86_64"
    ansible.builtin.debug:
      name: kernel
      state: present
      

 

# ansible-playbook  -i ../setup/inventory  conditional_playbook.yml