---
- name: Test playbook to run 
  hosts: all
  user: ec2-user
  become: true
  become_method: sudo
  tasks:
  - name: Add a line to a file if the file does not exist, without passing regexp
    ansible.builtin.lineinfile:
      path: /tmp/testfile
      regexp: '^192.168.1.99 foo.lab.net foo'
      line: '172.16.1.99 foo.lab.net foo'
    

 

# ansible-playbook  -i ../setup/inventory  mileinfile.yml