---
- name: Test playbook to run 
  hosts: all
  user: ec2-user
  become: true
  become_method: sudo
  tasks:
  - name: Install multiple package on Ubuntu
    when: ansible_facts['distribution'] == "Ubuntu"
    ansible.builtin.apt:
      name: "*"
      state: latest
    

 

# ansible-playbook  -i ../setup/inventory  update_ubuntu.yml