- name: Test playbook to run 
  hosts: all
  user: ec2-user
  become: true
  become_method: sudo
  vars:
    state: "present"
    php_version: "5.4.16"
  tasks:
  - name: Manage packages 
    ansible.builtin.package:
      name: telnet
      state: "{{ state }}"

  - name: Manage packages 
    ansible.builtin.package:
      name: unzip
      state: "{{ state }}"

  - name: Manage packages 
    ansible.builtin.package:
      name: lftp
      state: "{{ state }}"

  - name: Manage packages 
    ansible.builtin.package:
      name: elinks
      state: "{{ state }}"   

  - name: Manage packages 
    ansible.builtin.package:
      name: php-5.4.16
      state: "{{ state }}"   